// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Car_Sales.Models;

[Table("Dealer")]
public partial class Dealer
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "money")]
    public decimal Plane { get; set; }

    [Column(TypeName = "money")]
    public decimal Salary { get; set; }

    [InverseProperty("Dealer")]
    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}