// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Car_Sales.Models;

[Table("Model")]
public partial class Model
{
    [Key]
    public int id { get; set; }

    public int BrandId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "money")]
    public decimal BasePrice { get; set; }

    public int? AddonsId { get; set; }

    [ForeignKey("AddonsId")]
    [InverseProperty("Models")]
    public virtual Addon Addons { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Models")]
    public virtual Brand Brand { get; set; }

    [InverseProperty("Model")]
    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}