// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Car_Sales.Models;

public partial class Sale
{
    [Key]
    public int id { get; set; }

    public DateOnly Date { get; set; }

    public int ModelId { get; set; }

    public int DealerId { get; set; }

    public int ClientId { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Sales")]
    public virtual Client Client { get; set; }

    [ForeignKey("DealerId")]
    [InverseProperty("Sales")]
    public virtual Dealer Dealer { get; set; }

    [ForeignKey("ModelId")]
    [InverseProperty("Sales")]
    public virtual Model Model { get; set; }
}